### your site title here

title: Web Grid | A Grid based CSS Framework
description: Web Grid is a CSS grid based Grid system for easy web development. The minified Grid CSS weighs less than a KB.
#baseurl: /web-grid

analytics: UA-113964677-1

### exclude the instructions / write-up in the README.md

sass: 
    style: compressed

exclude:
- README.md


#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  

plugins: 
    - jekyll-seo-tag
